name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: docker login -u $(( secrets.DOCKER_HUB_USERNAME )) -p $(( secrets.DOCKER_HUB_ACCESS_TOKEN ))

    - name: Docker build
      run: docker build -f $(GITHUB_WORKSPACE)/docker/Dockerfile -t 