name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the docker image
      working-directory: test-dir
      run: docker build . --file Dockerfile --tag test-app