name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
      name: Build and push
      uses: docker/builld-push-action@v3
      with:
        context:
        file: ./Dockerfile
        push: true